name: dina_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_core_web: ^2.23.0
  firebase_auth: ^5.5.3
  provider: ^6.1.5
  get: ^4.7.2
  http: ^1.4.0
  intl: ^0.20.2
  uuid: ^4.5.1
  webview_flutter: ^4.10.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  fluttertoast: ^8.2.12
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  midtrans_sdk: ^1.1.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.png
    - assets/images/background.png
    - assets/images/facebook icon.png
    - assets/images/apple icon.png
    - assets/images/google icon.png
